server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dzmitry-karnyshou-db.cvwr7vc6qszc.us-east-1.rds.amazonaws.com:5432/postgres
    username: ...
    password: ...
  jpa:
    generate-ddl: true

aws:
  region: us-east-1

  s3:
    bucket:
      name: dzmitry-karnyshou-images

  sqs:
    queue:
      url: https://sqs.us-east-1.amazonaws.com/244976608449/dzmitry-karnyshou-uploads-notification-queue
      throughput: 10

  sns:
    topic:
      arn: arn:aws:sns:us-east-1:244976608449:dzmitry-karnyshou-uploads-notification-topic
      protocol: email